### PR TITLE
Added missing copyright header

### PR DESCRIPTION
**Pull request by insomniacslk**
Signed-off-by: Andrea Barberio <insomniac@slackware.it>

### CODE REVIEW

**Comment by insomniacslk** [comment]
Hopefully this won't create any problem with goose's parsing of that file

**Comment by marcoguerri** [comment]
Bah, this again, sorry. Doesn't the linter run as part of the integ test run in the container? Probably we already discussed this, I forgot what the outcome of this discussion was. 

> Hopefully this won't create any problem with goose's parsing of that file

Tested locally and it doesn't interfere with the parsing, anyway the integ test run will exercise the migration so it should confirm.

**Comment by insomniacslk** [comment]
> Bah, this again, sorry. Doesn't the linter run as part of the integ test run in the container? Probably we already discussed this, I forgot what the outcome of this discussion was.

The public linter ignores non-go files while the internal one doesn't. I can adjust the public linter to include sql, one sec

**Comment by insomniacslk** [comment]
Updated, but I have to change the regexp too, to match the sql-style comments, one sec

**Comment by insomniacslk** [comment]
> Updated, but I have to change the regexp too, to match the sql-style comments, one sec

Interestingly, it returns success, but it should fail because of the different comment style

**Comment by insomniacslk** [comment]
not sure why this is happening, but sounds like a bug in `checklicense`

**Comment by insomniacslk** [comment]
will look at that tomorrow

**Comment by insomniacslk** [comment]
@marcoguerri if that's OK I will merge this to fix the copyright header, and file an issue for checklicenses

**Comment by marcoguerri** [comment]
Sorry for the latency, yes, that's perfectly fine.

**Review by marcoguerri — APPROVED** [review]

**Pull request merged**
