### PR TITLE
Unify job and test descriptors in job structures

### PR DESCRIPTION
**Pull request by insomniacslk**
In this commit I've unified job and test descriptors in the `job.Request` object, as also hinted by @xaionaro in #76.

### CODE REVIEW

**Comment by insomniacslk** [comment]
This is still work in progress, please do not review yet

**Comment by insomniacslk** [comment]
I am making other changes in parallel, and I should probably split the two commits of this PR in two separate commits - the first one can already go, the second requires another intermediate change. I will force-push to remove the second commit

**Comment by insomniacslk** [comment]
This is ready to review now, please take a look

**Comment by marcoguerri** [comment]
Well, no, this unifies everything in `JobRequest`, probably the intention of #78 is to make `Job` itself serializable. Nevermind.

**Comment by insomniacslk** [comment]
That's as you say, #78 is slightly different and more laborious

**Pull request merged**
