### PR TITLE
add locks table

### PR DESCRIPTION
**Pull request by pmazzini**

### CODE REVIEW

**Comment by insomniacslk** [comment]
Ah I see this is still a draft, I didn't realize when reading from mobile

**Comment by pmazzini** [comment]
> Should this come together with the SQL locking plugin?

I want to agree on the schema first. I'll implement the plugin afterwards.

**Comment by marcoguerri** [comment]
Apologies for super late review... I have only one concern: what is `target_id` going to be? This is the problem that I was trying to address with #34. Several schema at the moment are not normalized (first and foremost `testevents`). Having a target id to use a foreign key would fix this problem, hence when I mentioned that events should not be the source of truth for which targets we are working on in this job, but instead there should be a dedicate table. How is `target_id` going to be used here?

**Comment by pmazzini** [comment]
I don't think #34 is a hard dependency for this but I may be wrong.

> How is target_id going to be used here?

Each lock request takes a `Target` as argument:
https://github.com/facebookincubator/contest/blob/master/pkg/target/locker.go#L31

And we can use its ID for storing a lock.

As long as the targetmanager fetches the Target with the proper ID, I think it should work. Am I missing something?

**Comment by pmazzini** [comment]
Thoughts?

**Comment by marcoguerri** [comment]
The same target, with the same ID, might be fetched at multiple times, so in practice that cannot be the primary key?

**Comment by marcoguerri** [comment]
Yeah, actually, I think is what we want. We'll just need make sure the framework enforces that IDs of target are unique (I don't think we do that explicitly anywhere, although we treat targets as comparable objects so target equality at the moment means ID, name and FQDN are equal).

**Pull request merged**
