### PR TITLE
[plugins/cmd] Added boolean emit_stdout and emit_stderr flags

### PR DESCRIPTION
**Pull request by insomniacslk**
If set to true, the plugin will emit stdout and/or stderr as payloads
for the respective events.
Default is not to emit anything, because events are stored on the DB,
and command output could be large.

Signed-off-by: Andrea Barberio <insomniac@slackware.it>

### CODE REVIEW

**Comment by insomniacslk** [comment]
Tested with the modified `start-literal.yaml` that sets emit_stdout and emit_stderr to true. The relevant parts in the job status:
```
                    "Data": {
                      "EventName": "CmdStdout",
                      "Payload": {
                        "Msg": "Title=Storage2345, ToUpper=STORAGE2345\n"
                      },
                      "Target": {
                        "FQDN": "",
                        "ID": "10.10.10.123",
                        "Name": "storage2345"
                      }
                    },

...

                    "Data": {
                      "EventName": "CmdStderr",
                      "Payload": {
                        "Msg": "Title=Storage2345, ToUpper=STORAGE2345\n"
                      },
                      "Target": {
                        "FQDN": "",
                        "ID": "10.10.10.123",
                        "Name": "storage2345"
                      }
                    },

```

**Comment by walterchris** [comment]
LGTM

**Review by tfg13 — APPROVED** [review]
GTG. Is `emit_stdout` descriptive enough so people understand it means "this will be saved into the database so maybe don't write too much"?

Also question: What happens if the payload is too long and the DB truncates it, will it end up with broken, unparsable JSON again?

**Comment by insomniacslk** [comment]
> GTG. Is `emit_stdout` descriptive enough so people understand it means "this will be saved into the database so maybe don't write too much"?

I think this needs to be addressed more generally with plugin documentation. We are lagging behind on that, but I would like to tackle that soon. Until then, I think comments in code should stop the gap, I've updated the code with a comment on the struct fields.

> Also question: What happens if the payload is too long and the DB truncates it, will it end up with broken, unparsable JSON again?

I added a warning about truncation, and this should be true and documented for any event that takes arbitrary payloads. Broken parsing.. is a bigger problem. It won't break the job, but it will break the status requests

**Comment by tfg13** [comment]
Ok, thats what I thought. Yeah go ahead and land it, none of the two are new problems, we need to address them in a more general way in any case.

**Comment by insomniacslk** [comment]
damn, git push returned error and I didn't notice. I'll push another PR with the comment change I mentioned above

**Comment by insomniacslk** [comment]
done at https://github.com/facebookincubator/contest/pull/191 , @tfg13 can you please take a look?

**Pull request merged**
