### PR TITLE
Add flag "skip_if_empty_host" to teststep "sshcmd"

### PR DESCRIPTION
**Pull request by xaionaro**
The flag allows to consider a target successful even if "host" field is empty (and ssh connection cannot be performed). It could be used if sshcmd should be executed not for all hosts. There are extra changes caused by "go fmt" and "go mod tidy", sorry about that.

# Test Plan

### Without flag

Job:
```json
{
    "JobName": "test",
    "Reporting": {
        "FinalReporters": [
            {
                "Name": "Noop",
                "Parameters": {}
            }
        ]
    },

    "RunInterval": "5s",
    "Runs": 1,
    "Tags": [
        "test",
        "csv"
    ],
    "TestDescriptors": [
        {
            "TargetManagerAcquireParameters": {
                "Targets": [
                    {
                        "ID": "259399886"
                    }
                ]
            },
            "TargetManagerName": "TargetList",
            "TargetManagerReleaseParameters": null,
            "TestFetcherFetchParameters": {
                "Steps": [
                    {
                        "label": "sshcmd_with_empty_host",
                        "name": "sshcmd",
                        "parameters": {
                            "executable": ["uptime"],
                            "host": ["{{ do_nothing \"\" }}"],
                            "user": ["wrongUser"],
                            "password:": ["wrongPassword"]
                        }
                    }
                ],
                "TestName": "Server provisioning"
            },
            "TestFetcherName": "literal"
        }
    ]
}
```

Result:
```
> select event_name from test_events where job_id='174272';
+----------------+
| event_name     |
+----------------+
| TargetAcquired |
| TargetIn       |
| TargetErr      |
+----------------+
3 rows in set (0.05 sec)
```

### With flag

Job:
```json
{
    "JobName": "test",
    "Reporting": {
        "FinalReporters": [
            {
                "Name": "Noop",
                "Parameters": {}
            }
        ]
    },

    "RunInterval": "5s",
    "Runs": 1,
    "Tags": [
        "test",
        "csv"
    ],
    "TestDescriptors": [
        {
            "TargetManagerAcquireParameters": {
                "Targets": [
                    {
                        "ID": "259399886"
                    }
                ]
            },
            "TargetManagerName": "TargetList",
            "TargetManagerReleaseParameters": null,
            "TestFetcherFetchParameters": {
                "Steps": [
                    {
                        "label": "sshcmd_with_empty_host",
                        "name": "sshcmd",
                        "parameters": {
                            "executable": ["uptime"],
                            "skip_if_empty_host": ["True"],
                            "host": ["{{ do_nothing \"\" }}"],
                            "user": ["wrongUser"],
                            "password:": ["wrongPassword"]
                        }
                    }
                ],
                "TestName": "Server provisioning"
            },
            "TestFetcherName": "literal"
        }
    ]
}
```

Result:
```
> select event_name from test_events where job_id='174270';
+----------------+
| event_name     |
+----------------+
| TargetAcquired |
| TargetOut      |
| TargetIn       |
+----------------+
3 rows in set (0.05 sec)
```

### CODE REVIEW

**Comment by rojer9-fb** [comment]
can you split formatting changes into separate commit?

also, we should enforce gofmt during lint run

**Review by rojer9-fb — APPROVED** [review]
other than that, seems reasonable

**Comment by xaionaro** [comment]
Splitted to two commits

**Review by insomniacslk — APPROVED** [review]
LGTM

**Pull request merged**
