### PR TITLE
fix(Fetcher)!: Forbid QueryField duplication

### PR DESCRIPTION
**Pull request by xaionaro**
This just another approach to implement QueryField duplication as a continuation of discussion at: https://github.com/facebookincubator/contest/pull/47

I could've reduce amount of code by replacing such code:
```go
type queryFieldJobID types.JobID

// QueryJobID sets the JobID field of the Query object
func QueryJobID(jobID types.JobID) QueryField                            { return queryFieldJobID(jobID) }
func (value queryFieldJobID) queryFieldPointer(query *Query) interface{} { return &query.JobID }
```
to
```go
// QueryJobID sets the JobID field of the Query object
type QueryJobID types.JobID
func (value QueryJobID) queryFieldPointer(query *Query) interface{} { return &query.JobID }
```
But it will be harder to read in autodocs, so I decided to preserve constructors (to get them generated in autodocs).

### CODE REVIEW

**Comment by xaionaro** [comment]
@marcoguerri : Here's another approach (but similar). Which is better in your opinion? The most unpleasant part is here:
https://github.com/facebookincubator/contest/pull/50/files#diff-d8ce936accdee0b4fe94622b57cc819bR10

**Comment by marcoguerri** [comment]
As mentioned in #47 , I see this as the best trade-off between delegating some responsibilities to the `QueryField` (only one, as a matter of fact :) ) and avoiding code duplication by having the check enforced in one single place. So, if you don't have additional concerns, I would go with this approach. Thank you for dissecting so thoroughly this problem :)

**Comment by xaionaro** [comment]
Agreed. Let's go with this approach :)

**Comment by marcoguerri** [comment]
I think at this point this can be closed :)

**Comment by xaionaro** [comment]
@marcoguerri : sorry, I did not understand. Why this PR was closed? Something is wrong? Or there's another implementation already?

**Comment by marcoguerri** [comment]
My bad, sorry. I have mistaken this for #47, which you already abandoned. There was nothing else to add here, so this can be merged, right?

**Comment by marcoguerri** [comment]
With #49 I introduced `RunID` field and broke the rebase :( Could you please add `queryFieldPointer` to `RunID`. Then this can be merged. Sorry for the trouble again :( I assumed the final version between #50 and #47 was already merged, instead #47 had been abandoned and this one was still here waiting for love :(

**Comment by tleunen** [comment]
# [Codecov](https://codecov.io/gh/facebookincubator/contest/pull/50?src=pr&el=h1) Report
> Merging [#50](https://codecov.io/gh/facebookincubator/contest/pull/50?src=pr&el=desc) into [master](https://codecov.io/gh/facebookincubator/contest/commit/196aef7471263ca4d06eab68324df5bbdc6d2f95&el=desc) will **decrease** coverage by `32.70%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/facebookincubator/contest/pull/50?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           master      #50       +/-   ##
===========================================
- Coverage   63.60%   30.89%   -32.71%     
===========================================
  Files          42       10       -32     
  Lines        2536      479     -2057     
===========================================
- Hits         1613      148     -1465     
+ Misses        702      320      -382     
+ Partials      221       11      -210     
```

| Flag | Coverage Δ | |
|---|---|---|
| #integration | `?` | |
| #unittests | `30.89% <53.57%> (+1.23%)` | :arrow_up: |

| [Impacted Files](https://codecov.io/gh/facebookincubator/contest/pull/50?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [pkg/pluginregistry/pluginregistry.go](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree#diff-cGtnL3BsdWdpbnJlZ2lzdHJ5L3BsdWdpbnJlZ2lzdHJ5Lmdv) | `18.42% <0.00%> (-65.79%)` | :arrow_down: |
| [pkg/pluginregistry/bundles.go](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree#diff-cGtnL3BsdWdpbnJlZ2lzdHJ5L2J1bmRsZXMuZ28=) | `0.00% <0.00%> (-53.97%)` | :arrow_down: |
| [pkg/lib/comparison/comparison.go](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree#diff-cGtnL2xpYi9jb21wYXJpc29uL2NvbXBhcmlzb24uZ28=) | `36.00% <0.00%> (-29.34%)` | :arrow_down: |
| [pkg/test/parameter.go](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree#diff-cGtnL3Rlc3QvcGFyYW1ldGVyLmdv) | `50.00% <0.00%> (-21.43%)` | :arrow_down: |
| [pkg/test/step.go](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree#diff-cGtnL3Rlc3Qvc3RlcC5nbw==) | `0.00% <0.00%> (-20.00%)` | :arrow_down: |
| [plugins/targetlocker/inmemory/inmemory.go](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree#diff-cGx1Z2lucy90YXJnZXRsb2NrZXIvaW5tZW1vcnkvaW5tZW1vcnkuZ28=) | `47.95% <0.00%> (-18.37%)` | :arrow_down: |
| [pkg/event/testevent/test.go](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree#diff-cGtnL2V2ZW50L3Rlc3RldmVudC90ZXN0Lmdv) | `47.05% <0.00%> (-41.84%)` | :arrow_down: |
| [pkg/event/common.go](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree#diff-cGtnL2V2ZW50L2NvbW1vbi5nbw==) | | |
| [pkg/target/locker.go](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree#diff-cGtnL3RhcmdldC9sb2NrZXIuZ28=) | | |
| [plugins/storage/rdbms/request.go](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree#diff-cGx1Z2lucy9zdG9yYWdlL3JkYm1zL3JlcXVlc3QuZ28=) | | |
| ... and [27 more](https://codecov.io/gh/facebookincubator/contest/pull/50/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/facebookincubator/contest/pull/50?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/facebookincubator/contest/pull/50?src=pr&el=footer). Last update [196aef7...1060c9b](https://codecov.io/gh/facebookincubator/contest/pull/50?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by xaionaro** [comment]
@marcoguerri :

> My bad, sorry. I mixed this up with #47, which you already abandoned.

No problem :)

> There was nothing else to add here, so this can be merged, right?

Yep)

> Could you please add `queryFieldPointer` to `RunID`? Then this can be merged. Sorry for the trouble again :(

Don't worry at all. Done :)

**Pull request merged**
