### PR TITLE
[pkg/runner] Do not `Run()` a TestStep until first Target

### PR DESCRIPTION
**Pull request by xaionaro**
Added logic to postpone calling `Run()` of a TestStep until
the first Target will be received. If no targets are received
and the channel is closed, then cancel running of the TestStep

Related: https://github.com/facebookincubator/contest/issues/101

# Test Plan

```
[xaionaro@void contest]$ go test ./... -tags integration
?       github.com/facebookincubator/contest/cmds/clients/contestcli-http       [no test files]
?       github.com/facebookincubator/contest/cmds/contest       [no test files]
?       github.com/facebookincubator/contest/pkg/api    [no test files]
?       github.com/facebookincubator/contest/pkg/cerrors        [no test files]
?       github.com/facebookincubator/contest/pkg/config [no test files]
?       github.com/facebookincubator/contest/pkg/event  [no test files]
?       github.com/facebookincubator/contest/pkg/event/frameworkevent   [no test files]
?       github.com/facebookincubator/contest/pkg/event/internal/querytools      [no test files]
?       github.com/facebookincubator/contest/pkg/event/internal/reflecttools    [no test files]
ok      github.com/facebookincubator/contest/pkg/event/testevent        (cached)
?       github.com/facebookincubator/contest/pkg/job    [no test files]
?       github.com/facebookincubator/contest/pkg/jobmanager     [no test files]
ok      github.com/facebookincubator/contest/pkg/lib/comparison (cached)
?       github.com/facebookincubator/contest/pkg/logging        [no test files]
ok      github.com/facebookincubator/contest/pkg/pluginregistry (cached)
ok      github.com/facebookincubator/contest/pkg/runner (cached)
?       github.com/facebookincubator/contest/pkg/storage        [no test files]
?       github.com/facebookincubator/contest/pkg/target [no test files]
ok      github.com/facebookincubator/contest/pkg/test   (cached)
?       github.com/facebookincubator/contest/pkg/types  [no test files]
?       github.com/facebookincubator/contest/plugins/listeners/httplistener     [no test files]
?       github.com/facebookincubator/contest/plugins/reporters/noop     [no test files]
?       github.com/facebookincubator/contest/plugins/reporters/targetsuccess    [no test files]
?       github.com/facebookincubator/contest/plugins/storage/memory     [no test files]
?       github.com/facebookincubator/contest/plugins/storage/rdbms      [no test files]
ok      github.com/facebookincubator/contest/plugins/targetlocker/inmemory      (cached)
ok      github.com/facebookincubator/contest/plugins/targetlocker/noop  (cached)
?       github.com/facebookincubator/contest/plugins/targetmanagers/csvtargetmanager    [no test files]
?       github.com/facebookincubator/contest/plugins/targetmanagers/targetlist  [no test files]
?       github.com/facebookincubator/contest/plugins/testfetchers/literal       [no test files]
?       github.com/facebookincubator/contest/plugins/testfetchers/uri   [no test files]
?       github.com/facebookincubator/contest/plugins/teststeps  [no test files]
?       github.com/facebookincubator/contest/plugins/teststeps/cmd      [no test files]
?       github.com/facebookincubator/contest/plugins/teststeps/echo     [no test files]
?       github.com/facebookincubator/contest/plugins/teststeps/example  [no test files]
?       github.com/facebookincubator/contest/plugins/teststeps/randecho [no test files]
?       github.com/facebookincubator/contest/plugins/teststeps/slowecho [no test files]
?       github.com/facebookincubator/contest/plugins/teststeps/sshcmd   [no test files]
?       github.com/facebookincubator/contest/plugins/teststeps/terminalexpect   [no test files]
?       github.com/facebookincubator/contest/tests/integ/common [no test files]
ok      github.com/facebookincubator/contest/tests/integ/events/frameworkevents 0.003s
ok      github.com/facebookincubator/contest/tests/integ/events/testevents      0.003s
ok      github.com/facebookincubator/contest/tests/integ/job    0.004s
ok      github.com/facebookincubator/contest/tests/integ/jobmanager     12.017s
ok      github.com/facebookincubator/contest/tests/integ/test   6.015s
?       github.com/facebookincubator/contest/tests/plugins/teststeps/channels   [no test files]
?       github.com/facebookincubator/contest/tests/plugins/teststeps/crash      [no test files]
?       github.com/facebookincubator/contest/tests/plugins/teststeps/fail       [no test files]
?       github.com/facebookincubator/contest/tests/plugins/teststeps/hanging    [no test files]
?       github.com/facebookincubator/contest/tests/plugins/teststeps/noop       [no test files]
?       github.com/facebookincubator/contest/tests/plugins/teststeps/noreturn   [no test files]
?       github.com/facebookincubator/contest/tests/plugins/teststeps/panicstep  [no test files]
```

### CODE REVIEW

**Comment by marcoguerri** [comment]
The approach looks fine to me, it's in line with what I think I would have done.

**Comment by insomniacslk** [comment]
Looks good to me too. There is just one linter warning to address before we can merge this:
```
+golangci-lint run --disable typecheck --enable deadcode --enable varcheck --enable staticcheck

pkg/runner/wait_for_first_target.go:47:3: S1000: should use for range instead of for { select {} } (gosimple)

		for {

		^

pkg/runner/wait_for_first_target_test.go:53:4: S1000: should use for range instead of for { select {} } (gosimple)

			for i := 0; i < 100; i++ {

			^
```

**Comment by insomniacslk** [comment]
uh.. after looking at it, it sounds like a false positive from the linter

**Comment by xaionaro** [comment]
> There is just one linter warning to address before we can merge this:

Fixed.

**Pull request merged**
